### PR TITLE
Fix invalid type error in docker-compose YAML

### PR DESCRIPTION
**Pull request by shamiq**
hi there! Docker must have updated the compose file requirements, as this wasn't building anymore. I made a couple changes so it'll build again.

### CODE REVIEW

**Comment by shamiq** [comment]
Errors I was getting on build:
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Service 'store' configuration key 'command' contains an invalid type, it should be a string, or an array

Errors on run:
ERROR: Cannot start container 1660af038ba4f2176fcf787b5ab22d07e1ef020fbff0c352b0fd41db9edff379: [8] System error: not a directory

**Comment by variadico** [comment]
Yeah, Docker has made some big changes since I originally wrote this. I talk about `boot2docker` in the readme, but that's deprecated now.

The new commands we should be using are these.
```
docker-machine create --driver virtualbox default
docker-machine start default
docker-machine env default
```
Someone (me or anyone else) should probably update the readme and add the new `docker-machine` stuff.

> ERROR: Validation failed in file './docker-compose.yml', reason(s):
Service 'store' configuration key 'command' contains an invalid type, it should be a string, or an array

Yup. I got the same error. Good job on the fix! :+1: 

> Errors on run

What does this mean? Do you mean you saw those errors after you ran `docker-compose up -d`? I didn't get that error, but my Go container didn't start up. After I ran `docker-compose up -d` again I could see the container running, but Nginx was still serving a 502 page.

I haven't investigated why. Maybe I can check this out this weekend.

**Comment by shamiq** [comment]
yea, a runtime issue on docker-compose up -d. I'm assuming when nginx attempted to mount the nginx.conf, it failed.

My go container started up without a problem after these changes. I ca try setting up a clean environment, and go from there. Did you do docker logs <gocontainer> to see why the container died?

**Comment by variadico** [comment]
Mmkay, I checked the logs. It was failing because the Postgres URI was wrong. Seems like Docker has changed some of the environment variables. But, I got it working. I can update `master`.

The `docker-compose.yml` changes worked great! Thank you very much for that! I wouldn't have noticed this was broken if you hadn't opened a PR!

Merging! :beers:

**Pull request merged**
